spring:
  application:
    name: eureka-server
  profiles:
    active: local

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
    
server:
  port: 8761
  
management:
  endpoints:
    web:
      exposure:
        include: '*'